Add image to feed
saberespoder/contenido pull request #13
Opened 2017-03-23 10:18 UTC by dvdbng

2017-03-23 10:20 UTC, FanaHOVA requested changes
Don't we have any specs for rss builders? Let's add some please

2017-03-23 10:38 UTC, query-string commented
@FanaHOVA it's a shame to admit it, but we don't have any specs in this project 😁  As I understand David needs this fix to interact with the feed on the new platform so it would be fair to merge changes just for now and add another issue about specs.

2017-03-23 10:42 UTC, query-string requested changes

2017-03-23 10:42 UTC, query-string commented on source/feed.xml.builder
> +      image_url = article.image.url.gsub(%r{^//}, 'https://')
In this case I would either use a helper to wrap image url transformation or added `article.image.url.gsub(%r{^//}, 'https://')` directly to  `xml.link` part. I don't really redefining variables inside iterators :nauseated_face:

2017-03-31 10:14 UTC, FanaHOVA approved these changes

2017-04-03 12:19 UTC, query-string approved these changes

2017-04-03 12:20 UTC, merged